### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by beayancan** [UKPLab/acl2020-empowering-active-learning#1]
Does the repository have samples available for the data folder? Or some structure to follow?

**Comment by Wuhn** [comment]
Hi Benjamin,

I added an example file for the data. 

To run the experiments with your data, it is probably easiest to modify the data loader in readers.load_data(input_file) . For each document, the remaining code expects a list of documents where each document consists of tokens with triples (token:str, label:int, features: numpy.array) . After adapting the reader, you should also adapt the model to match the input dimensions and you are good to go!

Best,
Ji-Ung
